[project]
name = "hw1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mystic98", email = "iantonov.zhenya@gmail.com" }
]
requires-python = ">=3.12.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
]

[project.scripts]
hw1 = "hw1:main"

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "ipython>=9.10.0",
    "jupyter-lsp>=2.3.0",
    "jupyterlab>=4.5.4",
    "ty>=0.0.17",
]
